// Planning AI Service - Generates SPEC.md

const fs = require('fs');
const path = require('path');

class PlanningAIService {
  constructor(config) {
    this.config = config;
  }

  /**
   * Generate SPEC.md for a ticket
   * In production, this would call OpenAI/Anthropic API
   */
  async generateSpec(ticket, workflowId) {
    console.log(`📋 Generating SPEC.md for Ticket #${ticket.ticketId}...`);
    
    // Simulate AI processing time
    await this.simulateAIProcessing();

    const spec = this.createSpecTemplate(ticket);
    
    // Save SPEC.md
    const specPath = path.join(
      this.config.piAgent.workspaceBase,
      workflowId,
      'SPEC.md'
    );
    
    // Create workspace directory
    const workspaceDir = path.dirname(specPath);
    if (!fs.existsSync(workspaceDir)) {
      fs.mkdirSync(workspaceDir, { recursive: true });
    }
    
    fs.writeFileSync(specPath, spec);
    
    console.log(`✅ SPEC.md generated at: ${specPath}`);
    
    return {
      specPath,
      specContent: spec,
      confidenceScore: 0.85
    };
  }

  createSpecTemplate(ticket) {
    return `# Ticket #${ticket.ticketId}: ${ticket.title}

## Problem Statement
${ticket.description}

## Proposed Solution
Based on the ticket description, this fix will:
1. Identify the root cause of the issue
2. Implement a targeted solution
3. Add appropriate tests to prevent regression

## Files to Modify
- \`src/api/routes.js\` - Add new endpoint for ${ticket.feature || 'requested functionality'}
- \`src/services/data-service.js\` - Update data handling logic
- \`tests/integration/api.test.js\` - Add test coverage

## Implementation Plan

### Step 1: Update Route Handler
\`\`\`javascript
// Add new route in src/api/routes.js
app.get('/api/status', (req, res) => {
  res.json({ status: 'active' });
});
\`\`\`

### Step 2: Update Service Layer
\`\`\`javascript
// Update data-service.js to handle new status checks
async function checkStatus() {
  // Implementation details
  return { active: true };
}
\`\`\`

### Step 3: Add Tests
\`\`\`javascript
// Add integration test
test('GET /api/status returns active status', async () => {
  const response = await request(app).get('/api/status');
  expect(response.status).toBe(200);
  expect(response.body.status).toBe('active');
});
\`\`\`

## Testing Strategy

### Unit Tests
- Test individual functions in isolation
- Mock external dependencies
- Coverage target: >80%

### Integration Tests
- Test API endpoints end-to-end
- Verify database interactions
- Test error scenarios

### Manual Verification
1. Start the application
2. Hit the new endpoint: \`curl http://localhost:3000/api/status\`
3. Verify response matches expected format

## Verification Checklist
- [ ] All unit tests pass
- [ ] Integration tests pass
- [ ] No linting errors
- [ ] Code follows project style guide
- [ ] Documentation updated
- [ ] No breaking changes introduced

## Risks & Mitigations

### Risk: Breaking existing functionality
**Mitigation**: Comprehensive test suite covers regression scenarios

### Risk: Performance impact
**Mitigation**: New endpoint is lightweight, no heavy computations

## Estimated Complexity
**Low-Medium** - Straightforward implementation with clear requirements

## Dependencies
None - This change is self-contained

---
*Generated by Planning AI on ${new Date().toISOString()}*
`;
  }

  async simulateAIProcessing() {
    // Simulate AI API call delay (1-3 seconds)
    const delay = 1000 + Math.random() * 2000;
    return new Promise(resolve => setTimeout(resolve, delay));
  }

  /**
   * Revise SPEC based on feedback
   */
  async reviseSpec(originalSpec, feedback, workflowId) {
    console.log(`🔄 Revising SPEC.md based on feedback...`);
    await this.simulateAIProcessing();
    
    const revisedSpec = `${originalSpec}\n\n## Revision Notes\n${feedback}\n\n*Revised on ${new Date().toISOString()}*`;
    
    const specPath = path.join(
      this.config.piAgent.workspaceBase,
      workflowId,
      'SPEC.md'
    );
    
    fs.writeFileSync(specPath, revisedSpec);
    
    return {
      specPath,
      specContent: revisedSpec,
      confidenceScore: 0.90
    };
  }
}

module.exports = PlanningAIService;
