// Configuration

module.exports = {
  // Mock AI configuration
  ai: {
    provider: 'mock',
    model: 'gpt-4',
    temperature: 0.3
  },

  // Approval configuration
  approval: {
    specTimeout: 24 * 60 * 60 * 1000, // 24 hours
    prTimeout: 48 * 60 * 60 * 1000,   // 48 hours
    defaultAssignee: 'developer@example.com'
  },

  // Pi Agent configuration
  piAgent: {
    maxExecutionTime: 30 * 60 * 1000, // 30 minutes
    workspaceBase: './poc/workspaces',
    allowedTools: ['read', 'write', 'bash', 'edit'],
    networkAccess: false
  },

  // QA configuration
  qa: {
    gates: [
      { name: 'Unit Tests', command: 'npm test', required: true },
      { name: 'Linting', command: 'npm run lint', required: true },
      { name: 'Build', command: 'npm run build', required: true }
    ]
  },

  // GitHub configuration
  github: {
    defaultBranch: 'main',
    prTemplate: `
## Ticket
Fixes: [Ticket #{{ticketId}}]({{ticketUrl}})

## Specification
[SPEC.md]({{specUrl}})

## Changes
{{summary}}

## QA Report
{{qaReportUrl}}

---
🤖 This PR was automatically generated by Pi Agent
    `.trim()
  },

  // Workspace configuration
  workspace: {
    cleanupAfterDays: 7,
    maxConcurrentWorkspaces: 5
  }
};
